# Minimal pre-commit configuration for eSTUDNA2
# https://pre-commit.com

repos:
  # Basic pre-commit hooks (whitespace, end-of-file, merge conflicts, YAML/JSON/TOML checks)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-toml

  # Ruff linter for Python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: [--fix]
        additional_dependencies: ["requests", "homeassistant"]

  # Optional spell checking
#  - repo: https://github.com/codespell-project/codespell
#    rev: v2.3.0
#    hooks:
#      - id: codespell
