name: CI – HACS + Pre-commit

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pre-commit and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit requests homeassistant

      - name: Run pre-commit
        run: pre-commit run --all-files
        env:
          RUFF_OUTPUT_FORMAT: github
          PRE_COMMIT_HOME: ~/.pre-commit-cache

  hacs:
    name: HACS Action
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v4

      - name: Run HACS Action
        uses: hacs/action@main
        with:
          category: integration
          skip_brand_validation: true
