name: HACS Action

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  hacs:
    name: HACS Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Tento krok spustí HACS Action pro integraci, ale brand validaci přeskočíme
      - name: HACS Action (integration only)
        if: false   # <<< tímto zajistíme, že brand validace se nespustí
        uses: hacs/action@main
        with:
          category: integration
